#!/bin/bash

# The local port for TeamServer
# TeamServer will be available at http://localhost:PORT/
PORT=8799

D="$(dirname "${BASH_SOURCE[0]}")"
cd "$D"

# Create a place to hold our TS files, so they persist between container runs
if ! [ -d "$D"/live-fs ]; then
    mkdir -p "$D"/live-fs
fi

pushd "$D"/live-fs

# Extract the initial TS install from the image if necessary
if ! [ -x bin/contrast-server.initd ]; then
    echo Extract install dir so it can persist between invocations
    docker run --rm contrast:v3.6 tar cvf - -C /usr/local/contrast . | tar xf -
fi

# Grab the hostname and port from the initial install config, since those
# are hard-coded into the config files generated during install

conf() {
    grep "$1" data/conf/general.properties | sed 's/=/ = /' | awk '{print $3}'
}
url() {
    conf teamserver\\.url
}
url_nohttp() {
    url | sed 's#^http[\\:]*//##'
}

HOSTNAME=`url_nohttp | sed 's#[\\]*:.*$##'`
iport=`url_nohttp | sed 's#^[^\\]*[\\]*:##' | sed 's#/.*$##'`

popd

# Use the right hostname, so the inter-process connections will work
docker run --rm --name contrast --hostname "$HOSTNAME" \
       -p $PORT:$iport \
       -v "$PWD"/live-fs:/usr/local/contrast \
       contrast:v3.6

